# This file was generated by GoReleaser. DO NOT EDIT.
cask "capturl-mcp" do
  name "capturl-mcp"
  desc "Capturl MCP Server"
  homepage "https://github.com/capturl/capturl-mcp"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capturl-mcp"

  on_macos do
    on_intel do
      url "https://github.com/capturl/capturl-mcp/releases/download/v#{version}/capturl-mcp_#{version}_darwin_amd64.tar.gz"
      sha256 "9ec72280bc8b1e22df2f1530170c7bdd38aac35c386b784017e693cc652bbdf1"
    end
    on_arm do
      url "https://github.com/capturl/capturl-mcp/releases/download/v#{version}/capturl-mcp_#{version}_darwin_arm64.tar.gz"
      sha256 "7bb68ce3dd68617b2e322fc404c3e79bb9f8ef2831b6c3d11b6846141b519723"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/capturl/capturl-mcp/releases/download/v#{version}/capturl-mcp_#{version}_linux_amd64.tar.gz"
      sha256 "98e67c4325fc5e881a625f5f91844bbe8955c341e368d17cf68b432ca2bc1108"
    end
    on_arm do
      url "https://github.com/capturl/capturl-mcp/releases/download/v#{version}/capturl-mcp_#{version}_linux_arm64.tar.gz"
      sha256 "422aa81d398fa96b3fe8971a3fd1123907d654bd2a72f9f53dd0c44d04d79656"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/capturl-mcp"]
    end
  end

  # No zap stanza required
end
