# This file was generated by GoReleaser. DO NOT EDIT.
cask "capturl-mcp" do
  name "capturl-mcp"
  desc "Capturl MCP Server"
  homepage "https://github.com/capturl/capturl-mcp"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capturl-mcp"

  on_macos do
    on_intel do
      url "https://github.com/capturl/capturl-mcp/releases/download/v#{version}/capturl-mcp_#{version}_darwin_amd64.tar.gz"
      sha256 "4602a28c251c339b7e327af24b57929a9a3418c32a557a48cc036f485de7eef8"
    end
    on_arm do
      url "https://github.com/capturl/capturl-mcp/releases/download/v#{version}/capturl-mcp_#{version}_darwin_arm64.tar.gz"
      sha256 "ec5a483bdc21bc537c5f94b3ac070acece573f7cd1ae83e953f93d6ccce49296"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/capturl/capturl-mcp/releases/download/v#{version}/capturl-mcp_#{version}_linux_amd64.tar.gz"
      sha256 "589fa45482dc99ac9bf313850f09bfe300b9118f268f0f0a7ebbce812f5d8648"
    end
    on_arm do
      url "https://github.com/capturl/capturl-mcp/releases/download/v#{version}/capturl-mcp_#{version}_linux_arm64.tar.gz"
      sha256 "31cd115c860a95d2013771023082d27ec550d2c3cb8a03b04943ec7471d0381d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/capturl-mcp"]
    end
  end

  # No zap stanza required
end
