# This file was generated by GoReleaser. DO NOT EDIT.
cask "capturl-mcp" do
  name "capturl-mcp"
  desc "Capturl MCP Server"
  homepage "https://github.com/capturl/capturl-mcp"
  version "0.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capturl-mcp"

  on_macos do
    on_intel do
      url "https://github.com/capturl/capturl-mcp/releases/download/v#{version}/capturl-mcp_#{version}_darwin_amd64.tar.gz"
      sha256 "4b784db626e73d35b7914eebe4dfe7de0212b395a1c4f0940b9c3718780f3029"
    end
    on_arm do
      url "https://github.com/capturl/capturl-mcp/releases/download/v#{version}/capturl-mcp_#{version}_darwin_arm64.tar.gz"
      sha256 "31b6bdb7c50085207dd139e0445e78d47157f7a26cc9c7cb6cd4169f6e538846"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/capturl/capturl-mcp/releases/download/v#{version}/capturl-mcp_#{version}_linux_amd64.tar.gz"
      sha256 "b7633ca354eaf9a135ca637588e1b3e99d5147050f8ffecfbdb8034e6bdd1d25"
    end
    on_arm do
      url "https://github.com/capturl/capturl-mcp/releases/download/v#{version}/capturl-mcp_#{version}_linux_arm64.tar.gz"
      sha256 "4195469469d1a48f7c28cad8dbc14342eb5d38d96689a6174b582bbda8524667"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/capturl-mcp"]
    end
  end

  # No zap stanza required
end
